@host = localhost:8080

### Register
POST http://{{host}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "test12@example.com",
	"username": "test12",
	"password": "test12"
}

### Login
POST http://{{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
	"username": "test1@example.com",
	"password": "test1"
}

